api:
  dashboard: true
  insecure: true # Don't expose publicly! Runs on port 8080

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik_gateway"

certificatesResolvers:
  letsEncrypt:
    acme:
      tlsChallenge: {}
      email: "appdev@sevenview.ca"
      storage: /letsencrypt/acme.json

global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
